import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Home.module.css'

export default function ThirdQuestion() {
  return (
    <>

     <div className={styles.container}>
        <Head>
          <title>Using Next.js</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Things a Product Advocate Might Do</h1>

          <p className={styles.description}>
            <i>Add a temporary redirect to your Next/Vercel project</i>
          </p>

          <p className={styles.description}>
            ...OOPS, this page isn&apos;t ready yet. Click the button to take you to another question.
          </p>

          <div className={styles.grid}>

            <a className={styles.card}>
              <Link href="/questions/fakepage">
                <h2>Home Page &larr;</h2>
              </Link>
            </a>

          </div>

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
   </>
  );
}