import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Home.module.css'

export default function ForthQuestion() {
  return (
    <>

     <div className={styles.container}>
        <Head>
          <title>Practice Email Responses</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Practice Email Responses</h1>

          <p className={styles.description}>
            <i>Please include one email response for each inquiry, just as if you were responding to a customer</i>
          </p>

          <p className={styles.description}>
            <h2>
              <u><b>Sales Inquiry: Do I need Enterprise?</b></u>
            </h2>
              <p><b>Subject:</b> Sales Lead for barnesandnoble.com</p>
              <p><b>Name:</b> Joe Fox</p>
              <p><b>Employees:</b> 1000+</p>
              <p><b>How can we help you:</b> New site launching soon using Next.js and we are thinking about using Vercel to host. I would like more information about the Enterprise option.</p>

                <a className={styles.letter}>
                  <p> LOOOOOOOOOOOL </p>
                </a>

            <h2>
              <u><b>Sales Inquiry: Would Pro or Enterprise fit better for my team?</b></u>
            </h2>
              <p><b>Subject:</b> Sales Lead for hipcamp.com</p>
              <p><b>Name:</b> Melissa Wright</p>
              <p><b>Employees:</b> 10-100</p>
              <p><b>How can we help you:</b> We are looking to re-platform our site and are considering Vercel. Would like to evaluate options to see if Pro or Enterprise would fit out needs better. Timeline is Q3. Can you help?</p>
 
          </a>
        </p>

          <h1 className={styles.return}>
            <Link href="/">Return to Main Page</Link>
          </h1>

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
   </>
  );
}